### PR TITLE
Migrate to Material design - define basic application theme.

### PR DESCRIPTION
**Pull request by johnjohndoe**
Depends on PR #11.

---

I colorized the status bar.
### Before

before
### After

after

### CODE REVIEW

**Comment by lstipakov** [comment]
Heart slider went outside of screen in bottom position:

Image of slider

**Comment by johnjohndoe** [comment]
I guess this isn't intended. Are you sure this hasn't been like this before?

**Comment by lstipakov** [comment]
Yep just double-checked, tested master and johnjohndoe-material-design
branches.

2015-10-05 18:03 GMT+03:00 Tobias Preuss notifications@github.com:

> I guess this isn't wanted. Are you sure this hasn't been like this before?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/help2/android/pull/10#issuecomment-145560933.

## 

-Lev

**Comment by johnjohndoe** [comment]
Hm. Strange. Then this might need some more effort. Do you have a clue since you created the slider?

**Comment by lstipakov** [comment]
ViewSwitcher.java
`int activityHeight = _activity.getWindow().getDecorView().getHeight();`
master branch returns 1776, this one 1920 (on Nexus 5).

**Comment by johnjohndoe** [comment]
The toolbar/actionbar is part of the layout now. This might be the reason the height changed. Maybe you have to substract the actionbar height or use another method to calculate the bare window height.

**Comment by lstipakov** [comment]
Merged with few additional changes:
- Different way of calculating activity height
- Show infobox on short tap on slider

**Pull request closed without merging**
