### PR TITLE
Boilerplate reduction

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@stipa Please wait. I need to fix something.

**Comment by johnjohndoe** [comment]
Problem fixed. Ready to merge.

**Comment by lstipakov** [comment]
What was wrong?

**Comment by johnjohndoe** [comment]
I forgot to initialize the `addr` field. This caused the `onClick` to do nothing. It's fixed now.

**Comment by johnjohndoe** [comment]
:+1:

**Pull request merged**
